name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
<<<<<<< HEAD
          MY_NAME: {name}
=======

>>>>>>> 6eb81e0173137386471941fabe3e448bda18d18f
